### ===================================
# **DATA & ANALYTICS V3**
# **MÓDULO 8** | 💻 Python for data
### **DataProject** | Proyecto EDA con Python
### **Autor** | Antonio Rojas Boquizo
### ===================================
### **Notebook** | 01_comprension_general_datos
Aquí explicaría el contenido. Aquí explicaría el contenido.   
Aquí explicaría el contenido. Aquí explicaría el contenido. Aquí explicaría el contenido.  
Aquí explicaría el contenido.  
Aquí explicaría el contenido. Aquí explicaría el contenido. Aquí explicaría el contenido.
Puede ser necesario simplificar este introducción.
### ===================================

In [20]:
import pandas as pd
pd.set_option('display.max_columns',None)

# pd para ver todas las columnas

from pathlib import Path

ruta_raw = Path('../data/raw')

In [22]:
df_bank = pd.read_csv(ruta_raw/'bank-additional.csv')

In [26]:
df_bank.sample(5)

# df_bank.head(5)
# df_bank.tail(5)

# puede optarse por df_bank.head(5) o df_bank.tail(5)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
13889,13986,NaN,technician,MARRIED,NaN,0.0,1.0,1.0,cellular,1973,2,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,963","5228,1",yes,18-julio-2019,46.080,-76.867,6ee4fb1c-427b-49c4-b022-d4106adabb3f
8692,8789,32.0,blue-collar,MARRIED,basic.9y,0.0,1.0,0.0,telephone,155,1,999,0,NONEXISTENT,1.4,"94,465","-41,8","4,866","5228,1",no,29-enero-2015,35.274,-113.429,a98598ba-d5ff-4ad5-a676-86a08e9378b1
24629,24751,55.0,blue-collar,SINGLE,basic.6y,0.0,1.0,0.0,cellular,204,2,999,0,NONEXISTENT,-0.1,"93,2",-42,"4,153","5195,8",no,21-marzo-2015,41.033,-75.735,9a8e84c8-a859-4b03-90a0-a2ce45519933
4572,4669,49.0,blue-collar,MARRIED,basic.4y,NaN,0.0,0.0,telephone,432,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,858",5191,no,30-abril-2019,45.777,-118.011,a6b2554b-7990-478d-9c04-361090f2a77d
14205,14302,29.0,services,MARRIED,high.school,0.0,1.0,0.0,cellular,407,2,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,962","5228,1",no,10-mayo-2015,44.601,-121.638,fedd6027-dcf4-42bf-ad59-ceccd70b52aa

separador es coma, perfectamente reconocido.

- 2 columnas que no están respecto al informe inicial, pero son fáciles de conseguir.
- 2 columnas nuevas que sí están.
- una de las columnas es un número de registro (añadida automaticamente)

In [25]:
df_bank.shape

(43000, 24)

In [18]:
print(f'Número de filas --------> {df_bank.shape[0]}')
print(f'Número de columnas -----> {df_bank.shape[1]}')

Número de filas --------> 43000
Número de columnas -----> 24

In [26]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 7.9 MB

In [27]:
df_bank.describe()

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.000000,37880.000000,34019.000000,41974.000000,41974.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,20651.099047,39.977112,0.000088,0.535998,0.155620,257.739279,2.567233,962.330953,0.174023,0.077128,36.856697,-95.939067
std,11868.770913,10.437957,0.009390,0.498708,0.362499,258.666033,2.772294,187.260394,0.497366,1.573898,7.225948,16.752282
min,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,24.396000,-124.997000
25%,10381.750000,32.000000,0.000000,0.000000,0.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,30.614750,-110.494250
50%,20642.500000,38.000000,0.000000,1.000000,0.000000,179.000000,2.000000,999.000000,0.000000,1.100000,36.761000,-95.899500
75%,30930.250000,47.000000,0.000000,1.000000,0.000000,319.000000,3.000000,999.000000,0.000000,1.400000,43.113250,-81.427750
max,41187.000000,98.000000,1.000000,1.000000,1.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,49.384000,-66.937000

In [ ]:
# .describe solo toma variables numéricas

In [27]:
df_bank.isna().sum()

Unnamed: 0           0
age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

In [30]:
df_bank.duplicated().sum()

np.int64(0)

In [31]:
df_bank["id_"].duplicated().sum()

np.int64(0)

In [31]:
df_bank.nunique()

Unnamed: 0        41032
age                  78
job                  11
marital               3
education             7
default               2
housing               2
loan                  2
contact               2
duration           1540
campaign             42
pdays                27
previous              8
poutcome              3
emp.var.rate         10
cons.price.idx       26
cons.conf.idx        26
euribor3m           309
nr.employed          11
y                     2
date               1825
latitude          20491
longitude         30448
id_               43000
dtype: int64

In [32]:
cat_cols = df_bank.select_dtypes(include="object").columns
for col in cat_cols:
    print(col, df_bank[col].unique()[:15], "\n")

job <StringArray>
[    'housemaid',      'services',        'admin.',   'blue-collar',
    'technician',       'retired',    'management',    'unemployed',
 'self-employed',             nan,  'entrepreneur',       'student']
Length: 12, dtype: str

marital <StringArray>
['MARRIED', 'SINGLE', 'DIVORCED', nan]
Length: 4, dtype: str

education <StringArray>
[           'basic.4y',         'high.school',            'basic.6y',
            'basic.9y', 'professional.course',                   nan,
   'university.degree',          'illiterate']
Length: 8, dtype: str

contact <StringArray>
['telephone', 'cellular']
Length: 2, dtype: str

poutcome <StringArray>
['NONEXISTENT', 'FAILURE', 'SUCCESS']
Length: 3, dtype: str

cons.price.idx <StringArray>
['93,994',      nan, '94,465', '93,918', '93,444', '93,798',   '93,2',
 '92,756', '92,843', '93,075', '92,893', '92,963', '92,469', '92,201',
 '92,379']
Length: 15, dtype: str

cons.conf.idx <StringArray>
['-36,4', '-41,8', '-42,7', '-36,1', '-40,4',   '-42', '-45,9',   '-50',
 '-47,1', '-46,2', '-40,8', '-33,6', '-31,4', '-29,8', '-26,9']
Length: 15, dtype: str

euribor3m <StringArray>
['4,857',     nan, '4,856', '4,855', '4,859',  '4,86', '4,858', '4,864',
 '4,865', '4,866', '4,967', '4,961', '4,959', '4,958',  '4,96']
Length: 15, dtype: str

nr.employed <StringArray>
[  '5191', '5228,1', '5195,8', '5176,3', '5099,1', '5076,2', '5017,5',
 '5023,5', '5008,7', '4991,6', '4963,6']
Length: 11, dtype: str

y <StringArray>
['no', 'yes']
Length: 2, dtype: str

date <StringArray>
[     '2-agosto-2019', '14-septiembre-2016',    '15-febrero-2019',
  '29-noviembre-2015',      '29-enero-2017', '26-septiembre-2015',
      '25-enero-2019', '25-septiembre-2017',      '18-enero-2018',
   '2-noviembre-2016',  '30-noviembre-2015',      '17-abril-2016',
      '14-junio-2016',     '25-agosto-2015', '19-septiembre-2016']
Length: 15, dtype: str

id_ <StringArray>
['089b39d8-e4d0-461b-87d4-814d71e0e079',
 'e9d37224-cb6f-4942-98d7-46672963d097',
 '3f9f49b5-e410-4948-bf6e-f9244f04918b',
 '9991fafb-4447-451a-8be2-b0df6098d13e',
 'eca60b76-70b6-4077-80ba-bc52e8ebb0eb',
 'd63ede72-0b6d-45b1-8872-385ac6897f65',
 '5e3483e5-236d-437d-8351-541f9d09b9dd',
 '87fdc08b-30ae-4dab-803f-561ecdf27ff0',
 '87b79988-2be5-419d-88f4-56655852c565',
 'ea6b7d04-9271-4c0a-a01f-07795d164aba',
 '8d700df5-0c33-4517-8cf8-92e1c92c9c12',
 'ca5c0d7a-8bbd-42b3-8351-1074c5be011a',
 '66a752e2-b2f1-440c-9a8f-cc3b10d74dd0',
 '54b1ea8a-a909-45d9-9562-775b64ac9c29',
 '3a7b7570-aba9-40bc-9f80-3433d064b5b7']
Length: 15, dtype: str

C:\Users\Hp\AppData\Local\Temp\ipykernel_35780\3780482766.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df_bank.select_dtypes(include="object").columns

EXCEL

In [33]:
df_hoja01 = pd.read_excel("../data/raw/customer-details.xlsx",sheet_name=0)

In [34]:
df_hoja01

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...,...,...,...,...,...,...,...
20110,20110,114469,0,2,2012-10-28,13,25f35a3f-0fd2-4e6a-b4d5-74fa1a1f4cfc
20111,20111,82207,0,1,2012-02-10,27,a3d2d088-3781-44ea-9944-a4a40df51285
20112,20112,135009,0,0,2012-09-14,17,3769cb72-26be-40f2-9a93-f752fc96d628
20113,20113,8486,1,1,2012-07-04,18,d507f6b3-a030-46d7-9615-61fe3f6b8028
20114,20114,144419,1,0,2012-04-12,29,8299f0a6-e4c0-49fc-87ab-81308b70f80f

In [35]:
hojas = pd.read_excel(ruta_raw/'customer-details.xlsx', sheet_name=None)
print(hojas.keys())

dict_keys(['2012', '2013', '2014'])

In [36]:
for name, df in hojas.items():
    print(f"--- {name} ---")
    print(df.shape)
    print(list(df.columns))
    print(df.isna().sum().sum(), "nulos en total")
    print(df.duplicated().sum(), "duplicados")
    print()

--- 2012 ---
(20115, 7)
['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth', 'ID']
0 nulos en total
0 duplicados

--- 2013 ---
(8965, 7)
['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth', 'ID']
0 nulos en total
0 duplicados

--- 2014 ---
(14090, 7)
['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth', 'ID']
0 nulos en total
0 duplicados

In [39]:
first = next(iter(hojas.values()))
first.info()
first.head()

<class 'pandas.DataFrame'>
RangeIndex: 20115 entries, 0 to 20114
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         20115 non-null  int64
 1   Income             20115 non-null  int64
 2   Kidhome            20115 non-null  int64
 3   Teenhome           20115 non-null  int64
 4   Dt_Customer        20115 non-null  datetime64[us]
 5   NumWebVisitsMonth  20115 non-null  int64
 6   ID                 20115 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.1 MB

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [38]:
df_bank["id_"].head(), df_bank["id_"].dtype

(0    089b39d8-e4d0-461b-87d4-814d71e0e079
 1    e9d37224-cb6f-4942-98d7-46672963d097
 2    3f9f49b5-e410-4948-bf6e-f9244f04918b
 3    9991fafb-4447-451a-8be2-b0df6098d13e
 4    eca60b76-70b6-4077-80ba-bc52e8ebb0eb
 Name: id_, dtype: str,
 <StringDtype(storage='python', na_value=nan)>)

In [39]:
first["ID"].head(), first["ID"].dtype

(0    089b39d8-e4d0-461b-87d4-814d71e0e079
 1    e9d37224-cb6f-4942-98d7-46672963d097
 2    3f9f49b5-e410-4948-bf6e-f9244f04918b
 3    9991fafb-4447-451a-8be2-b0df6098d13e
 4    eca60b76-70b6-4077-80ba-bc52e8ebb0eb
 Name: ID, dtype: str,
 <StringDtype(storage='python', na_value=nan)>)

## Problemas detectados
**bank-additional.csv**
- [ ] ... nulos en columnas X, Y
- [ ] ... duplicados en id_
- [ ] `date` tiene tipo object

**customer-details.xlsx**
- [ ] ...

**Para el merge**
- [ ] ...